my:
  greeting: A new greeting from config server. Hello again, refresh this
  list:
    values: One, Two, Three, Four
db:
  connection: connection-string-here-from-config-server
  host: 127.0.0.1
  port: 1200
